from . import res_teacher
from . import res_student
from . import student_type
from . import teacher_designation
from . import teacher_type
from . import subject
from . import timetable 
from . import standard
from . import attandance